# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/users/khaledali/desktop/Reliable-Data-Transport-Protocol-with-UDP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/users/khaledali/desktop/Reliable-Data-Transport-Protocol-with-UDP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/users/khaledali/desktop/Reliable-Data-Transport-Protocol-with-UDP/CMakeFiles /mnt/c/users/khaledali/desktop/Reliable-Data-Transport-Protocol-with-UDP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/users/khaledali/desktop/Reliable-Data-Transport-Protocol-with-UDP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rdt_with_udp

# Build rule for target.
rdt_with_udp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdt_with_udp
.PHONY : rdt_with_udp

# fast build rule for target.
rdt_with_udp/fast:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/build
.PHONY : rdt_with_udp/fast

server/src/server.o: server/src/server.cpp.o

.PHONY : server/src/server.o

# target to build an object file
server/src/server.cpp.o:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/server.cpp.o
.PHONY : server/src/server.cpp.o

server/src/server.i: server/src/server.cpp.i

.PHONY : server/src/server.i

# target to preprocess a source file
server/src/server.cpp.i:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/server.cpp.i
.PHONY : server/src/server.cpp.i

server/src/server.s: server/src/server.cpp.s

.PHONY : server/src/server.s

# target to generate assembly for a file
server/src/server.cpp.s:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/server.cpp.s
.PHONY : server/src/server.cpp.s

server/src/sr_worker.o: server/src/sr_worker.cpp.o

.PHONY : server/src/sr_worker.o

# target to build an object file
server/src/sr_worker.cpp.o:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/sr_worker.cpp.o
.PHONY : server/src/sr_worker.cpp.o

server/src/sr_worker.i: server/src/sr_worker.cpp.i

.PHONY : server/src/sr_worker.i

# target to preprocess a source file
server/src/sr_worker.cpp.i:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/sr_worker.cpp.i
.PHONY : server/src/sr_worker.cpp.i

server/src/sr_worker.s: server/src/sr_worker.cpp.s

.PHONY : server/src/sr_worker.s

# target to generate assembly for a file
server/src/sr_worker.cpp.s:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/sr_worker.cpp.s
.PHONY : server/src/sr_worker.cpp.s

server/src/utils.o: server/src/utils.cpp.o

.PHONY : server/src/utils.o

# target to build an object file
server/src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/utils.cpp.o
.PHONY : server/src/utils.cpp.o

server/src/utils.i: server/src/utils.cpp.i

.PHONY : server/src/utils.i

# target to preprocess a source file
server/src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/utils.cpp.i
.PHONY : server/src/utils.cpp.i

server/src/utils.s: server/src/utils.cpp.s

.PHONY : server/src/utils.s

# target to generate assembly for a file
server/src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/rdt_with_udp.dir/build.make CMakeFiles/rdt_with_udp.dir/server/src/utils.cpp.s
.PHONY : server/src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... rdt_with_udp"
	@echo "... edit_cache"
	@echo "... server/src/server.o"
	@echo "... server/src/server.i"
	@echo "... server/src/server.s"
	@echo "... server/src/sr_worker.o"
	@echo "... server/src/sr_worker.i"
	@echo "... server/src/sr_worker.s"
	@echo "... server/src/utils.o"
	@echo "... server/src/utils.i"
	@echo "... server/src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

